version: "3.7"
services:
  apache: # веб-сервер apache
    build:
      context: infrastructure/docker
      dockerfile: development/apache/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/usr/local/apache2/htdocs/
    depends_on:
      - php-fpm

  php-fpm: # php-fpm для веб сервера
    build:
      context: infrastructure/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./:/template