version: "3.7"
services:
    nginx: # веб-сервер nginx
        build:
            context: infrastructure/docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./:/template
        depends_on:
            - php-fpm
    php-fpm: # php для веб сервера
        build:
            context: infrastructure/docker
            dockerfile: development/php-fpm/Dockerfile
        volumes:
            - ./:/template
    php-cli: # php консольный вариант для технических целей
        build:
            context: infrastructure/docker
            dockerfile: development/php-cli/Dockerfile
        volumes:
            - ./:/template
    mariadb:
        image: mariadb:10 # база данных mariadb
        environment:
            MYSQL_ROOT_PASSWORD: template
            MYSQL_DATABASE: template
        volumes:
            - mariadb:/var/lib/mysql
            - ./infrastructure/docker/development/mariadb/conf.d/:/etc/mysql/conf.d/
        ports:
            - "3306:3306"
volumes:
    mariadb: