version: "3.7"
services:
    nginx-alpine: # веб-сервер nginx
        build:
            context: ./infrastructure/docker/development/nginx-alpine
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./:/template
        depends_on:
            - php-fpm-alpine
    php-fpm-alpine: # php-fpm для веб сервера
        build:
            context: ./infrastructure/docker/development/php-fpm-alpine
            dockerfile: Dockerfile
        volumes:
            - ./:/template
    php-cli-alpine: # php консольный вариант для технических целей
        build:
            context: ./infrastructure/docker/development/php-cli-alpine
            dockerfile: Dockerfile
        volumes:
            - ./:/template
    mariadb-ubuntu:
        image: mariadb:10 # база данных mariadb
        environment:
            MYSQL_ROOT_PASSWORD: template
            MYSQL_DATABASE: template
        volumes:
            - mariadb-ubuntu:/var/lib/mysql
            - ./infrastructure/docker/development/mariadb-ubuntu/conf.d/:/etc/mysql/conf.d/
        ports:
            - "3306:3306"
volumes:
    mariadb-ubuntu: