version: "3.7"
services:
  nginx-debian: # веб-сервер nginx
    build:
      context: ./infrastructure/docker/development/nginx-debian
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/template
    depends_on:
      - php-fpm-debian

  php-fpm-debian: # php-fpm для веб сервера
    build:
      context: ./infrastructure/docker/development/php-fpm-debian
      dockerfile: Dockerfile
    volumes:
      - ./:/template