version: "3.7"
services:
  apache-alpine: # веб-сервер apache
    build:
      context: ./infrastructure/docker/development/apache-alpine
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/usr/local/apache2/htdocs/
    depends_on:
      - php-fpm-alpine

  php-fpm-alpine: # php-fpm для веб сервера
    build:
      context: ./infrastructure/docker/development/php-fpm-alpine
      dockerfile: Dockerfile
    volumes:
      - ./:/template