<?php

declare(strict_types=1);

namespace Tests;

class ArrayTest extends AbstractTestCase
{
    protected array $array;

    public function setUp(): void
    {
        $this->array = [];
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        unset($this->array);
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testOne() {
        $this->assertCount(0, $this->array);
    }

    public function testTwo() {
        $this->array = [1,2,3,4,5];
        $this->assertCount(5, $this->array);
    }

}
