<?php

declare(strict_types=1);

namespace Tests;

class MethodsTest extends AbstractTestCase
{
    public static function setUpBeforeClass(): void
    {
        echo __METHOD__ . "\n";

        parent::setUpBeforeClass();
    }

    public static function tearDownAfterClass(): void
    {
        echo __METHOD__ . "\n";
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }

    protected function assertPreConditions(): void
    {
        echo __METHOD__ . "\n";
        parent::assertPreConditions(); // TODO: Change the autogenerated stub
    }

    protected function assertPostConditions(): void
    {
        echo __METHOD__ . "\n";
        parent::assertPostConditions(); // TODO: Change the autogenerated stub
    }

    public function testOne(){
        $this->assertTrue(true);
        $this->assertTrue(true);
    }

    public function testTwo(){
        $this->assertTrue(true);
        $this->assertTrue(true);
    }
}